### ISSUE TITLE
Support for compiling with Cython?

### ISSUE THREAD

**Issue by Baekalfen** [a-hurst/pysdl2-dll#1]
I'm no expert on SDL2, compiling or linking, but I'm having some trouble shifting to this package compared to installing SDL2 through brew on Mac.

You'll likely remember, that we discussed your package in reference to PyBoy https://github.com/Baekalfen/PyBoy/issues/87 .

Your package works completely fine when using PyPy (i.e. when not compiling), but it seems to miss some binaries (`sdl2-config`) and some `.lib` files for compiling. You can see the brew package installs using `make install` in the formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl2.rb

Do you know, if there is a way to get the missing files through your package? Weirdly enough, the runtime binaries and the development libraries on https://www.libsdl.org/download-2.0.php seems to be the exact same.

**Comment by a-hurst** [comment]
Hey @Baekalfen,

As long as it won't dramatically change the complexity and difficulty of maintaining what's currently a fairly simple package, I'd be happy to help make this work! Could you point out what .lib files appear to be missing with the pysdl2-dll package according to your build attempts? I believe all that `sdl2-config` does is set the appropriate linker and include flags for SDL2 based on where you installed it, so that could be something that's either replaced completely in a build script with some code doing the same thing, or alternatively be provided as a `python -m sdl2-config` module that performs the same service (but doesn't conflict with the actual binary if installed).

Another issue I can think of here is that there currently aren't any headers at all bundled with the Windows DLLs because I never thought they'd be needed, but as long as I can bundle them with the regular SDL2 release DLLs instead of the development libraries that shouldn't be too hard to fix.

**Comment by Baekalfen** [comment]
Ok, so `sdl2-config --cflags ―libs` returns these two lines:
```
-I/usr/local/include/SDL2 -D_THREAD_SAFE
-L/usr/local/lib -lSDL2
```

The first directory points to all the header files. I think these are equivalent to what `pysdl2-dll` installs. The second directory contains symlinks to these files:

```
$ ls -la /usr/local/Cellar/sdl2/2.0.12_1/lib/
total 6368
drwxr-xr-x   9 mads  staff      288 Mar 11 02:36 .
drwxr-xr-x  11 mads  staff      352 Apr 10 00:06 ..
drwxr-xr-x   3 mads  staff       96 Mar 11 02:36 cmake
-rw-r--r--   1 mads  staff  1176616 Apr 10 00:06 libSDL2-2.0.0.dylib
-r--r--r--   1 mads  staff  1839816 Mar 11 02:36 libSDL2.a
lrwxr-xr-x   1 mads  staff       19 Mar 11 02:36 libSDL2.dylib -> libSDL2-2.0.0.dylib
-r--r--r--   1 mads  staff   232472 Mar 11 02:36 libSDL2_test.a
-r--r--r--   1 mads  staff      832 Mar 11 02:36 libSDL2main.a
drwxr-xr-x   3 mads  staff       96 Apr 10 00:06 pkgconfig
```

I have no idea where to source these, if it isn't from `make install`. But compiling on the client, would likely require Xcode to be installed etc. It's not as simple as the package is now.

**Comment by Baekalfen** [comment]
I can see that you are using Travis. Would it be possible to compile them on the Travis VM and ship them as part of the PyPi package?

**Comment by a-hurst** [comment]
From the extensions, it looks like those files other than the .dylibs are just static libraries that Homebrew provides in case you want to build SDL2 directly into your binary instead of just dynamically linking to it. In the majority of cases, the contents of the framework (which contains the SDL2 dynamic library) should be all you need to build something with SDL2 on macOS, as long as the include/linking paths are right.

Since you're wanting a solution that doesn't require end-users to need a compiler, though, I think pointing your binaries to the pysdl2-dll binaries is going to be the key challenge (you could dynamically link your binaries against a different SDL2 using CI and it would still work fine on a user's machine as long as it could find SDL2 binaries to link to). To my knowledge, dynamic linking for macOS and Linux requires binaries to point to the absolute or relative paths of any dynamic libraries they link to, so you would need to be able to safely assume the path to pysdl2-dll inside site-package would always be the same relative to the PyBoy binary in site-packages (this actually might be the case, but would need testing). On Windows, dynamic linking is a whole other bizarre world I don't know much about, except that there are only certain directories it will search for a DLL and that it'll search them in a specific order. You may need to resort to static linking or bundling within the PyBoy package folder in order for it to work properly.

Hope that helps!

**Comment by Baekalfen** [comment]
It's not a major priority at this moment, so I think I'll close the issue again for now. But thanks for your help. I think the solution in the future might better be to statically link SDL2 for the CPython/Cython build, and use your package for PyPy.
