### ISSUE TITLE
macOS filename miss .so

### ISSUE THREAD

**Issue by wolanx** [a-hurst/pysdl2-dll#27]
SDL2 should convert to SDL2.so,
It will cause the build tool not to find it correctly, I debugged it, but don't know how to fix it

<img width="257" alt="image" src="https://github.com/a-hurst/pysdl2-dll/assets/9441015/648ed9c9-3e1e-4851-80d9-d10dffd66046">

**Comment by a-hurst** [comment]
> It will cause the build tool not to find it correctly, I debugged it, but don't know how to fix it

What build tool are you trying to use? Can you explain your use-case a bit more?

All pysdl2-dll does on macOS is bundle the contents of the official frameworks (e.g. the .dmg [here](https://github.com/libsdl-org/SDL/releases/tag/release-2.28.1)) in a Python package, with unnecessary header files and symlinks stripped out for a smaller wheel size. As such, the binaries don't have an `.so` extension because the binaries in the official frameworks don't have an `.so` extension either:

![Screen Shot 2023-07-29 at 2 28 38 PM](https://github.com/a-hurst/pysdl2-dll/assets/18648066/8ab960b9-8f22-41ed-a0bd-a3eeb1e1b19b)

Is the issue that you're trying to compile a C Python extension against SDL2 and have it link against pysdl2-dll's binaries so you don't have to include them in your own package?

**Comment by wolanx** [comment]
I'm using nuitka. Although it happens in nuitka. But other lib no such problem, I'm guessing some kind of convention was not followed.

At win:
![image](https://github.com/a-hurst/pysdl2-dll/assets/9441015/689b1a59-265d-460e-8406-1204f79cd510)

At macOS
<img width="1183" alt="image" src="https://github.com/a-hurst/pysdl2-dll/assets/9441015/4630d294-1ed7-4483-8025-459dbc1b7a74">

Win works fine, they are all in the dll directory, but mac is not.

**Comment by wolanx** [comment]
MacOS M2
After `brew install SDL2`
The problem was automatically fixed.
